import Foundation

/// Single source of truth for App Group registration defaults.
///
/// Keep this list aligned with user-facing settings only; derived runtime
/// state should not be added here unless it is persisted across launches.
public enum PreferenceDefaults {
    public static let registrationValues: [String: Any] = [
        AppGroupKey.didCompleteOnboarding: false,
        AppGroupKey.hasRequestedAccessibilityPrompt: false,
        AppGroupKey.pendingFinderBridgeHostLaunch: false,
        AppGroupKey.appLanguage: "system",
        AppGroupKey.dockClickBehaviorEnabled: false,
        AppGroupKey.windowPreviewsEnabled: false,
        AppGroupKey.folderQuickLookEnabled: true,
        AppGroupKey.folderQuickLookShowWarning: true,
        AppGroupKey.finderNewFileMenuEnabled: true,
        AppGroupKey.dockLockEnabled: false,
        AppGroupKey.hoverOpenDelay: 0.4,
        AppGroupKey.previewSize: "standard",
        AppGroupKey.previewCloseButtonVisible: true,
        AppGroupKey.headerActionsEnabled: true,
        AppGroupKey.middleClickCloseEnabled: true,
        AppGroupKey.dragOutEnabled: true,
        AppGroupKey.spaceMagnifyEnabled: true,
        AppGroupKey.suppressEmptyPreviews: true,
        AppGroupKey.showHoverWhenMinimized: true,
        AppGroupKey.trafficLightEnabled: true,
        AppGroupKey.trafficLightSide: "trailing",
        AppGroupKey.killButtonVisible: false,
        AppGroupKey.lockedScreenIDs: [String](),
        AppGroupKey.windowSnappingEnabled: false,
        AppGroupKey.windowSnappingShortcuts: "",
        AppGroupKey.fileCutPasteEnabled: false,
        AppGroupKey.snapLayoutsEnabled: false,
        AppGroupKey.windowSwitcherEnabled: false,
        AppGroupKey.volumeMixerEnabled: false,
        AppGroupKey.clipboardHistoryEnabled: false,
        AppGroupKey.notchCaffeinateWidget: false,
        AppGroupKey.notchProductivityWidget: false,
        AppGroupKey.notchPomodoroMinutes: 25.0,
        AppGroupKey.notchMirrorEnabled: false,
        AppGroupKey.pauseOnHeadphonesRemoved: true,
        AppGroupKey.quickPanelDisplays: true,
        AppGroupKey.quickPanelStats: true,
        AppGroupKey.quickPanelSound: true,
        AppGroupKey.quickPanelMic: true,
        AppGroupKey.quickPanelMeetings: true,
        AppGroupKey.quickPanelAwake: true,
        AppGroupKey.displayKeysEnabled: false,
        AppGroupKey.brightnessScheduleEnabled: false,
        AppGroupKey.brightnessDayStart: 420.0,
        AppGroupKey.brightnessNightStart: 1260.0,
        AppGroupKey.brightnessDayLevel: 0.8,
        AppGroupKey.brightnessNightLevel: 0.35,
        AppGroupKey.awakeDisplayMaySleep: false,
        AppGroupKey.awakeWhileApps: [String](),
        AppGroupKey.awakeOnPower: false,
        AppGroupKey.awakeWhileDownloading: false,
        AppGroupKey.awakeLidClosed: false,
        AppGroupKey.clipboardPanelEnabled: false,
        AppGroupKey.meetingsEnabled: false,
        AppGroupKey.screenshotShelfEnabled: false,
        AppGroupKey.finderExtraMenuEnabled: true,
        AppGroupKey.notchQuickNoteText: "",
        AppGroupKey.notchEnabled: false,
        AppGroupKey.notchMusicWidget: true,
        AppGroupKey.notchBatteryWidget: true,
        AppGroupKey.notchShelfWidget: true,
        AppGroupKey.notchMediaControlsEnabled: true,
        AppGroupKey.notchShowAppIcon: true,
        AppGroupKey.notchShowAlbumArt: true,
        AppGroupKey.notchCalendarEnabled: true,
        AppGroupKey.notchCalendarStyle: "text",
        AppGroupKey.notchBatteryStyle: "symbol",
        AppGroupKey.notchHoverDelay: 0.2,
        AppGroupKey.notchShelfURLs: [String]()
    ]
}

public enum Localizer {
    public static var currentLocale: Locale {
        let lang = (AppGroup.copySuiteValue(forKey: AppGroupKey.appLanguage) as? String) ?? "system"
        let localeLang: String
        if lang == "system" {
            let preferred = Locale.preferredLanguages.first ?? "en"
            let current: String
            if #available(macOS 13, iOS 16, tvOS 16, watchOS 9, *) {
                current = Locale.current.language.languageCode?.identifier ?? "en"
            } else {
                current = Locale.current.languageCode ?? "en"
            }
            let isTr = preferred.hasPrefix("tr") || current.hasPrefix("tr")
            localeLang = isTr ? "tr" : "en"
        } else {
            localeLang = lang
        }
        return Locale(identifier: localeLang)
    }

    public static func string(_ key: String) -> String {
        let localeLang = currentLocale.identifier
        return translations[localeLang]?[key] ?? translations["en"]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "menu.about": "About Augment",
            "menu.settings": "Settings…",
            "menu.permissions": "Accessibility Permission…",
            "menu.caffeinate": "Keep Mac Awake",
            "perm.accessibility": "Accessibility",
            "perm.screen_recording": "Screen Recording",
            "perm.automation_finder": "Finder automation",
            "perm.needed": "Needs %@ permission",
            "perm.grant": "Grant",
            "short.previews": "Dock previews",
            "short.dockclick": "Click to minimize",
            "short.docklock": "Dock display lock",
            "short.snap": "Window snapping",
            "short.layouts": "Layout picker",
            "short.switcher": "Window switcher",
            "short.newfile": "New File menu",
            "short.folderql": "Folder preview",
            "short.filecut": "File cut & paste",
            "short.notch": "Notch",
            "short.mixer": "Volume mixer",
            
            "perm.granted": "Granted",
            "perm.used_by": "Used by: %@",
            "permissions.subtitle_v2": "Augment only asks for a permission when you turn on a feature that needs it.",
            "permissions.footer_v2": "If a switch looks on in System Settings but the status here stays empty, remove Augment from that list with “−” and grant it again — an older build's approval doesn't carry over.",
            "page.dock": "Dock",
            "page.dock_sub": "What happens when you point at or click an app in the Dock.",
            "page.dock_previews": "Window previews",
            "page.windows": "Windows",
            "page.windows_sub": "Arrange windows and switch between them from the keyboard.",
            "page.finder": "Finder",
            "page.finder_sub": "Additions to Finder's menus, Quick Look and shortcuts.",
            "page.finder_cut": "Cut and paste",
            "page.sound": "Sound & Display",
            "page.sound_sub": "Per-app volume and external monitor controls.",
            "page.menubar": "Quick Panel",
            "page.menubar_sub": "Choose what the panel under Augment's menu bar icon shows. Right-click the icon for Augment's menu.",
            "page.awake": "Keep awake",
            "page.awake_sub": "Prevents the display from sleeping until you turn it off.",
            "general.summary": "%d of %d features on",
            "general.all_off": "All off", "general.on": "On",
            "general.perms_ok": "All permissions granted",
            "general.perms_missing": "%d permission(s) missing",
            "general.app": "App",
            "general.launch_at_login": "Open Augment at login",
            "menu.quit": "Quit Augment",
            "settings.title": "Augment Settings",
            "about.description": "The small things macOS leaves out — for the Dock, windows, Finder, the notch, sound and displays.",
            "about.version": "Version",
            
            
            
            // General Pane
            
            "general.features": "Features",
            
            "general.language": "Language",
            "general.lang_system": "System Language",
            "general.lang_en": "English",
            "general.lang_tr": "Türkçe",
            // Sidebar / tab titles
            "tab.general": "General",
            
            
            
            "tab.notch": "Notch",
            "tab.permissions": "Permissions",

            // Feature titles & subtitles
            "feature.hover_title": "Window previews on Dock hover",
            "feature.hover_subtitle": "Live thumbnails appear when you linger on a Dock icon.",
            "feature.dockClick_title": "Toggle minimize on Dock click",
            
            
            
            
            "feature.snapping_title": "Window snapping",
            
            
            
            
            "menubar.no_match": "No matches.",
            
            
            "page.awake_title": "Keep Awake", "page.awake_page_sub": "Stop your Mac from sleeping — by hand, for a while, or automatically.",
            "awake.manual_section": "Now", "quick.modules": "Show in the panel", "quick.microphone": "Microphone",
            "quick.modules_footer": "Sections only appear when they have something to show (for example meetings need Upcoming meetings on the Notch page).",
            "notch.search": "Search", "notch.copied": "Copied",
            "notch.drop_shelf": "Shelf", "notch.drop_zip": "Zip", "notch.tab_mirror": "Mirror",
            "notch.airdrop_all": "AirDrop All", "notch.zip_all": "Zip All to Downloads", "notch.clear_shelf": "Clear Shelf",
            "mirror.title": "Mirror", "mirror.desc": "A camera tab in the notch to check how you look before a call. The camera is only on while the tab is open.",
            "mirror.denied": "Augment isn't allowed to use the camera.", "mirror.no_camera": "No camera found",
            "awake.reason_app": "Kept awake: %@ is open",
            "awake.reason_power": "Kept awake: on power",
            "awake.reason_download": "Kept awake: download in progress",
            "awake.on_power": "While connected to power",
            "awake.downloading": "While a download is in progress",
            "awake.apps": "While these apps are open",
            "awake.add_app": "Add App…",
            "awake.auto_section": "Keep awake automatically",
            "awake.auto_footer": "Any of these keeps your Mac awake on its own; the manual switch and durations above still work too. Downloads are detected from unfinished files in your Downloads folder.",
            "awake.display_sleep": "Let the display sleep",
            "awake.display_sleep_desc": "Keep the Mac running (downloads, renders, music) but allow the screen to turn off.",
            "awake.lid": "Stay awake with the lid closed",
            "awake.lid_desc": "Works while the Mac is connected to power — macOS always sleeps on battery when the lid closes.",
            "awake.options_section": "Options",
            "displays.keys_title": "Brightness & volume keys control monitors",
            "displays.keys_desc": "The keyboard's brightness keys adjust the screen under the pointer, and volume keys drive a monitor's speakers over DDC. The built-in screen keeps working as usual.",
            "displays.keys_section": "Keyboard",
            "displays.schedule_title": "Day & night brightness",
            "displays.schedule_desc": "Switches every screen to a day or night level at the times you choose. Changes you make in between are kept.",
            "displays.schedule_section": "Schedule",
            "displays.schedule_day": "Day from",
            "displays.schedule_night": "Night from",
            "meetings.title": "Upcoming meetings",
            "meetings.desc": "Shows your next event in the notch and quick panel, and opens the notch 5 minutes before it starts with a Join button for Zoom, Meet or Teams links.",
            "meetings.no_access": "Augment can't read your calendars yet.",
            "meetings.join": "Join",
            "meetings.now": "Now",
            "meetings.in_minutes": "In %d min",
            "meetings.today": "Today",
            "perm.open_settings": "Open Settings",
            "screenshots.title": "Screenshots to the shelf",
            "screenshots.desc": "New screenshots drop onto the notch shelf so you can drag them straight into a chat or email.",
            "notch.extras_section": "More in the notch",
            "clip.panel_title": "Clipboard panel (⇧⌘V)",
            "clip.panel_desc": "Search your clipboard history, pin favourites and paste with Return or ⌘1–⌘9.",
            "clip.section": "Clipboard",
            "clip.search": "Search clipboard",
            "clip.hint": "Return pastes · ⌘1–9 quick paste · ⌘P pins · Esc closes",
            "clip.pin": "Pin",
            "finder.extra_title": "Copy Path & Open in Terminal",
            "finder.extra_desc": "Adds both to Finder's right-click menu.",
            "finder.extras_section": "More in Finder",
            "finderext.on": "Finder extension is on",
            "finderext.off": "Finder extension is off",
            "finderext.off_desc": "macOS installs it switched off. Turn on Augment under Finder extensions — otherwise the right-click items and the cut badge don't appear.",
            "finderext.enable": "Turn On…",
            "finderext.later": "Later",
            "finderext.alert_title": "Turn on Augment's Finder extension",
            "finderext.alert_body": "Augment's right-click items in Finder (New File, Copy Path, Open in Terminal) and the cut badge need its Finder extension, which macOS installs switched off. Click Turn On and enable Augment in the list that opens.",
            "finder.copy_path": "Copy Path",
            "stats.title": "System", "stats.cpu": "CPU", "stats.memory": "Memory", "stats.network": "Network",
            "stats.temperature": "Temperature",
            "stats.thermal_nominal": "Normal", "stats.thermal_fair": "Warm", "stats.thermal_serious": "Hot", "stats.thermal_critical": "Very hot",
            "finder.new_text_name": "untitled",
            "tour.welcome_title": "Welcome to Augment",
            "tour.welcome_body": "The small things macOS leaves out — for the Dock, windows, Finder, the notch, sound and displays. Everything starts switched off: turn on what you want, and Augment asks for a permission only when a feature needs it.",
            "tour.panel_title": "Quick panel",
            "tour.panel_body": "Click Augment's menu bar icon for every screen's brightness, sound and per-app volume, the microphone and Keep Awake. Right-click the icon for Augment's menu.",
            "tour.notch_title": "The notch",
            "tour.notch_body": "Move the pointer to the notch: music, a file shelf, clipboard, a note and Pomodoro, plus brightness and volume. Drag files onto it to keep them, AirDrop or zip them.",
            "tour.windows_title": "Dock & windows",
            "tour.windows_body": "Hover a Dock icon to preview its windows, press ⌥Tab for a switcher with thumbnails, ⌘← → to snap windows and ⌃⌥Space for layouts.",
            "tour.finder_title": "Finder",
            "tour.finder_body": "Right-click for New File or Folder, Copy Path and Open in Terminal; ⌘X cuts files for real. These need Augment's Finder extension switched on.",
            "tour.ready_title": "You're set",
            "tour.ready_body": "Open Settings and switch on the features you'd like. You can take this tour again from Augment's menu.",
            "tour.next": "Continue",
            "tour.back": "Back",
            "tour.skip": "Skip",
            "tour.open_settings": "Open Settings",
            "menu.tour": "Quick Tour…",
            "finder.new_folder": "Folder", "finder.new_folder_name": "untitled folder",
            "finder.open_terminal": "Open in Terminal",
            "quick.all_displays": "All displays",
            "quick.mic_on": "Microphone on",
            "quick.mic_off": "Microphone muted",
            "mixer.default_output": "Default output",
            "mixer.pause_headphones": "Pause playback when headphones are removed",
            "mixer.pause_headphones_desc": "Like macOS does on its own: taking out AirPods or unplugging headphones pauses music and videos instead of playing on the speakers.",
            "mixer.output_help": "Where this app's sound plays",
            "notch.awake_on": "Awake", "notch.awake_off": "Keep awake",
            "notch.awake_turn_off": "Turn Off", "notch.awake_indefinite": "Until I turn it off",
            "notch.awake_hours": "%d hours", "notch.awake_minutes": "%d minutes",
            "notch.awake_help": "Keeps your Mac and display awake. Right-click to choose how long.",
            "notch.hour_short": "h", "notch.minute_short": "m",
            "notch.tab_note": "Note", "notch.pomodoro_help": "Focus timer — right-click to change its length",
            "notch.pomodoro_length": "Pomodoro length", "notch.minutes_value": "%d min",
            
            
            
            
            // Hover Pane
            
            "hover.delay": "Hover delay",
            "hover.minimized": "Minimized",
            "hover.timing": "Timing",
            "hover.delay_desc": "How long the cursor needs to dwell on a Dock icon before the preview appears.",
            "hover.appearance": "Appearance",
            "hover.size": "Preview size",
            "hover.suppress": "Suppress empty previews",
            "hover.suppress_desc": "Never pop a panel for apps that aren't running or have no windows.",
            "hover.header_actions": "Header actions",
            "hover.header_actions_desc": "Hovering the title surfaces Close All / Minimize All shortcuts.",
            "hover.magnify": "Magnify on Space",
            "hover.magnify_desc": "Press Space while the hover preview is open to expand it. Other apps (for example Finder’s Quick Look) will not also receive that Space key while the preview is up.",
            "hover.interactions": "Interactions",
            "hover.middle_click": "Middle-click closes window",
            "hover.middle_click_desc": "Wheel-click a thumbnail (or a Dock icon) to close all of its windows.",
            "hover.drag_out": "Drag-out to focus",
            "hover.drag_out_desc": "Drag a thumbnail out of the panel to focus that window in place.",
            "hover.instant": "Instant",
            "hover.minimize_all": "Minimize All",
            "hover.close_all": "Close All",
            "hover.no_open_windows": "No open windows",

            // Window Controls Pane
            
            "controls.show": "Show traffic-light controls",
            "controls.show_desc": "Close, minimize, and zoom dots appear on hover, matching macOS.",
            "controls.side": "Side",
            "controls.force_quit": "Force quit button",
            "controls.force_quit_desc": "Renders a destructive bolt icon on the opposite edge of every preview.",
            "controls.legacy": "Show legacy close glyph",
            "controls.legacy_desc": "When traffic lights are off, fall back to the small × button on hover.",
            "controls.layout": "Layout",
            // Dock Click Pane
            
            "dock_click.behavior": "Click Behaviour",
            "dock_click.toggle_minimize": "Toggle minimize on Dock click",
            "dock_click.toggle_minimize_desc": "Click the active app's Dock icon to hide its windows; click again to bring them back. Other apps keep their macOS default behavior.",
            
            
            // Finder Pane
            
            "finder.menu": "\u{201C}New File with Augment\u{201D} menu",
            "finder.menu_desc": "Adds the categorized contextual menu in Finder.",
            "finder.folder_ql": "Folder Quick Look hierarchy",
            "finder.folder_ql_desc": "Press Space on a folder to see its tree, sizes, and summaries.",
            "finder.warning": "Show warning when disabled",
            "finder.warning_desc": "If off, macOS shows its default folder icon instead of Augment\u{2019}s \u{201C}feature off\u{201D} message.",
            "finder.behavior": "Behaviour",
            "finder.footer": "Finder/Quick Look extensions are managed by macOS. After toggling these, you may need to right-click in Finder once for the menu to refresh.",
            "finder.menu_title": "New File with Augment",
            "finder.category_coding": "Coding",
            "finder.category_office": "Microsoft Office",
            "finder.category_data": "Data",
            "finder.category_project": "Project Files",
            "finder.category_text": "Text",
            "finder.template_word": "Word Document (.docx)",
            "finder.template_excel": "Excel Workbook (.xlsx)",
            "finder.template_rtf": "Rich Text (.rtf)",
            "finder.template_env": "Environment (.env)",
            "finder.template_txt": "Plain Text (.txt)",
            "finder.error_cannot_determine_title": "Cannot create file",
            "finder.error_cannot_determine_msg": "Augment couldn't determine which folder to use. Right-click again and try once more.",
            "finder.error_generic_title": "Could not create file",
            "finder.error_no_permission": "Augment doesn’t have permission to write in this location. Try another folder or grant access in Privacy settings.",
            "finder.error_read_only": "This volume is read-only, so a new file can’t be created here.",
            // Displays Pane
            
            "displays.lock": "Lock Dock to chosen displays",
            "displays.lock_desc": "Augment ignores Dock interactions on other screens and lifts the cursor out of their Dock-summon zone, so macOS won't slide the Dock onto a non-selected display.",
            "displays.dock_lock": "Dock Lock",
            "displays.connected": "Connected Displays",
            "displays.refresh": "Refresh display list",
            "displays.fallback": "If no display is selected, Augment falls back to the screen under the cursor.",
            "displays.id": "Display ID",
            
            "displays.section": "Displays", "displays.rescan": "Rescan",
            "displays.none": "No displays found.",
            "displays.footer": "Built-in and Apple displays use macOS's own brightness. Other monitors are controlled over DDC/CI (like MonitorControl); if a monitor doesn't support it, Augment dims the picture instead.",
            "displays.method_native": "Built-in control", "displays.method_ddc": "DDC/CI", "displays.method_software": "Software dimming",
            "quick.displays": "Displays", "quick.sound": "Sound",
            "quick.enable_mixer": "Per-app volume: turn on the Volume Mixer",
            "quick.awake_off_title": "Off", "quick.awake_remaining": "%@ left",
            "quick.off": "Off", "quick.awake_duration": "Duration",
            
            
            
            
            // Snapping Pane
            
            "snapping.enable": "Enable window snapping",
            "snapping.enable_desc": "Use keyboard shortcuts to tile windows to halves or maximize them.",
            "snapping.toggle": "Master Toggle",
            "snapping.press": "Press shortcut…",
            "snapping.change": "Change",
            "snapping.reset_help": "Reset to default",
            "snapping.shortcuts": "Shortcuts",
            "snapping.shortcuts_desc": "Click \"Change\" next to a direction, then press your desired key combination. Defaults are ⌘ + Arrow Keys.",
            "snapping.preview": "Preview",
            "snapping.left": "Left",
            "snapping.right": "Right",
            
            "snapping.left_half": "Left Half",
            "snapping.right_half": "Right Half",
            "snapping.maximize": "Maximize",
            "snapping.restore_center": "Restore / Center",

            // Cut & Paste
            "cutpaste.file_title": "Finder File Cut",
            "cutpaste.file_desc": "Adds a real Cut (⌘X) to Finder: cut items get a scissors badge, ⌘V in another folder moves them, ⌘Z moves them back. Esc or ⌘Z before pasting cancels the cut.",

            "snaplayouts.section": "Snap Layouts",
            "snaplayouts.title": "Snap-Zone Picker",
            "snaplayouts.desc": "A Windows 11-style flyout with halves, quarters, and thirds — pick a zone to snap the frontmost window into it.",
            "snaplayouts.trigger": "Show picker",
            "snaplayouts.footer": "Press the shortcut near where you want the window to land — the picker opens next to your cursor. Escape cancels.",

            "switcher.section": "Window Switcher",
            "switcher.title": "Thumbnail Window Switcher",
            "switcher.desc": "Hold Option and tap Tab to cycle through live thumbnails of every open window, release Option to jump to it.",
            "switcher.trigger": "Show switcher",
            "switcher.footer": "Bound to ⌥Tab (not ⌘Tab) so the system's own App Switcher is never touched — this one switches between individual windows, not just apps.",

            
            "mixer.toggle": "Volume Mixer",
            "mixer.enable": "Enable Volume Mixer",
            "mixer.enable_desc": "Set a separate volume for each app, independent of the system volume.",
            "mixer.footer": "Uses macOS 14.2+'s Core Audio process-tap API (no virtual audio driver, no private APIs) — the same technique open-source Mac volume mixers use. Requires macOS 14.2 or later.",
            "mixer.apps": "Running Apps",
            "mixer.no_apps": "No apps currently playing audio.",
            "mixer.unsupported": "Volume Mixer needs macOS 14.2 or later.",

            // Notch Pane
            "notch.title": "Interactive Notch",
            "notch.subtitle": "Turn the MacBook camera notch into a dynamic hub for music, battery & files.",
            "notch.enable": "Enable Interactive Notch",
            "notch.enable_desc": "Show an expandable overlay that sits behind the physical notch.",
            "notch.no_notch": "No notched display detected. This feature requires a MacBook with a camera notch (2021 or later).",
            "notch.toggle": "Master Toggle",
            "notch.music": "Music & Media widget",
            "notch.music_desc": "Shows the currently playing media from system apps.",
            "notch.playback": "Show playback controls",
            "notch.app_icon": "Show source app icon",
            "notch.album_art": "Show album art",
            "notch.hover": "Hover delay",
            "notch.battery": "Battery indicator",
            "notch.battery_desc": "Apple-style battery level and charging status.",
            "notch.battery_style": "Battery style",
            "notch.gauge": "Gauge",
            "notch.symbol": "Symbol",
            "notch.percent": "Percent",
            "notch.calendar": "Calendar widget",
            "notch.calendar_desc": "Shows the current day and date.",
            "notch.calendar_style": "Calendar style",
            "notch.compact": "Compact",
            "notch.badge": "Badge",
            "notch.text": "Text",
            "notch.shelf": "File shelf",
            "notch.shelf_desc": "Drag files onto the notch for quick access; double-click to open.",
            "notch.widgets": "Widgets",
            "notch.widgets_desc": "Hover over the notch area to expand it and see your widgets. Drag files onto it to use the shelf.",
            "notch.preview": "Preview",
            "notch.no_widgets": "No widgets selected",
            
            "notch.caffeinate": "Keep-Awake Button",
            "notch.caffeinate_desc": "Shows a toggle in the notch's top bar to keep the Mac awake.",
            "notch.clipboard": "Clipboard History",
            "notch.clipboard_desc": "Adds a Clipboard tab next to the file shelf with your recent copies.",
            "notch.shelf_tab_files": "Files",
            "notch.shelf_tab_clipboard": "Clipboard",
            "notch.clipboard_empty": "Nothing copied yet.",
            "notch.productivity": "Quick Note & Pomodoro",
            "notch.productivity_desc": "A scratchpad and a focus timer inside the notch.",
            "notch.quick_note_placeholder": "Quick note…",
            
            "notch.pomodoro_done": "Pomodoro finished 🍅",
            "notch.drop_files": "Drop files to pin",
            "notch.open": "Open",
            "notch.reveal": "Reveal in Finder",
            "notch.copy": "Copy File",
            "notch.remove": "Remove",
            // Permissions Pane
            "permissions.title": "Permissions",
            
            
            
            
            
            // Enums
            "size.small": "Small",
            "size.standard": "Standard",
            "size.large": "Large",
            "side.left": "Left",
            "side.right": "Right",
            "click.toggle_minimize": "Toggle Minimize",
            "click.close_all_windows": "Close All Windows",
            "click.quit_app": "Quit App",
            "click.system_default": "System Default",
            "click.toggle_minimize_subtitle": "Click to hide, click again to bring windows back.",
            "click.close_all_windows_subtitle": "Sends the close action to every standard window of the active app.",
            "click.quit_app_subtitle": "Asks the app to quit, like ⌘Q.",
            "click.system_default_subtitle": "Augment doesn't intercept the click; macOS handles it as usual.",
            "effect.system": "System",
            "effect.genie": "Genie",
            "effect.scale": "Scale",
            "effect.suck": "Suck",
            "effect.system_subtitle": "Use the macOS-wide minimize animation.",
            "effect.genie_subtitle": "Classic curl-into-the-Dock animation.",
            "effect.scale_subtitle": "Quick rectangular shrink, faster than Genie.",
            "effect.suck_subtitle": "Compact swirl into the Dock icon."
        ],
        "tr": [
            "menu.about": "Augment Hakkında",
            "menu.settings": "Ayarlar…",
            "menu.permissions": "Erişilebilirlik İzni…",
            "menu.caffeinate": "Mac'i Uyanık Tut",
            "perm.accessibility": "Erişilebilirlik",
            "perm.screen_recording": "Ekran Kaydı",
            "perm.automation_finder": "Finder otomasyonu",
            "perm.needed": "%@ izni gerekiyor",
            "perm.grant": "İzin Ver",
            "short.previews": "Dock önizlemeleri",
            "short.dockclick": "Tıklayınca küçült",
            "short.docklock": "Dock ekran kilidi",
            "short.snap": "Kenara yaslama",
            "short.layouts": "Yerleşim seçici",
            "short.switcher": "Pencere değiştirici",
            "short.newfile": "Yeni dosya menüsü",
            "short.folderql": "Klasör önizleme",
            "short.filecut": "Dosya kes-yapıştır",
            "short.notch": "Notch",
            "short.mixer": "Ses mikseri",
            
            "perm.granted": "Verildi",
            "perm.used_by": "Kullanan: %@",
            "permissions.subtitle_v2": "Augment bir izni yalnızca o izne ihtiyaç duyan bir özelliği açtığında ister.",
            "permissions.footer_v2": "Sistem Ayarları'nda düğme açık görünüyor ama burada durum boş kalıyorsa, Augment'i o listeden “−” ile kaldırıp izni yeniden ver. Eski bir sürüme verilen izin yeni sürüme geçmiyor.",
            "page.dock": "Dock",
            "page.dock_sub": "Dock'taki bir uygulamanın üzerine gelince veya tıklayınca olanlar.",
            "page.dock_previews": "Pencere önizlemeleri",
            "page.windows": "Pencereler",
            "page.windows_sub": "Pencereleri klavyeyle yerleştir ve aralarında geçiş yap.",
            "page.finder": "Finder",
            "page.finder_sub": "Finder menülerine, Quick Look'a ve kısayollara eklenenler.",
            "page.finder_cut": "Kes ve yapıştır",
            "page.sound": "Ses ve Ekran",
            "page.sound_sub": "Uygulama başına ses ve harici monitör kontrolleri.",
            "page.menubar": "Hızlı Panel",
            "page.menubar_sub": "Menü çubuğundaki Augment ikonuna tıklayınca açılan panelde neler görüneceğini seç. Augment menüsü için ikona sağ tıkla.",
            "page.awake": "Uyanık tut",
            "page.awake_sub": "Sen kapatana kadar ekranın uykuya geçmesini engeller.",
            "general.summary": "%d / %d özellik açık",
            "general.all_off": "Kapalı", "general.on": "Açık",
            "general.perms_ok": "Tüm izinler verildi",
            "general.perms_missing": "%d izin eksik",
            "general.app": "Uygulama",
            "general.launch_at_login": "Girişte Augment'i aç",
            "menu.quit": "Augment'ten Çık",
            "settings.title": "Augment Ayarları",
            "about.description": "macOS'ta eksik kalan küçük dokunuşlar — Dock, pencereler, Finder, notch, ses ve ekranlar için.",
            "about.version": "Sürüm",
            
            
            
            // General Pane
            
            "general.features": "Özellikler",
            
            "general.language": "Dil",
            "general.lang_system": "Sistem Dili",
            "general.lang_en": "English",
            "general.lang_tr": "Türkçe",
            // Sidebar / tab titles
            "tab.general": "Genel",
            
            
            
            "tab.notch": "Notch",
            "tab.permissions": "İzinler",

            // Feature titles & subtitles
            "feature.hover_title": "Dock simgesi üzerinde pencere önizlemeleri",
            "feature.hover_subtitle": "Bir Dock simgesinin üzerinde beklediğinizde canlı küçük resimler görünür.",
            "feature.dockClick_title": "Dock tıklamasında küçültmeyi aç/kapat",
            
            
            
            
            "feature.snapping_title": "Pencere hizalama (snapping)",
            
            
            
            
            "menubar.no_match": "Eşleşme yok.",
            
            
            "page.awake_title": "Uyanık Tut", "page.awake_page_sub": "Mac'in uykuya geçmesini engelle — elle, bir süreliğine ya da kendiliğinden.",
            "awake.manual_section": "Şimdi", "quick.modules": "Panelde göster", "quick.microphone": "Mikrofon",
            "quick.modules_footer": "Bölümler yalnızca gösterecek bir şey olduğunda çıkar (örneğin toplantılar için Notch sayfasındaki Yaklaşan toplantılar açık olmalı).",
            "notch.search": "Ara", "notch.copied": "Kopyalandı",
            "notch.drop_shelf": "Raf", "notch.drop_zip": "Zip", "notch.tab_mirror": "Ayna",
            "notch.airdrop_all": "Hepsini AirDrop ile Gönder", "notch.zip_all": "Hepsini Zip Yap (İndirilenler)", "notch.clear_shelf": "Rafı Temizle",
            "mirror.title": "Ayna", "mirror.desc": "Görüşmeden önce nasıl göründüğüne bakmak için notch'ta kamera sekmesi. Kamera yalnızca sekme açıkken çalışır.",
            "mirror.denied": "Augment'in kamerayı kullanma izni yok.", "mirror.no_camera": "Kamera bulunamadı",
            "awake.reason_app": "Uyanık: %@ açık",
            "awake.reason_power": "Uyanık: şarjda",
            "awake.reason_download": "Uyanık: indirme sürüyor",
            "awake.on_power": "Şarja takılıyken",
            "awake.downloading": "İndirme sürerken",
            "awake.apps": "Bu uygulamalar açıkken",
            "awake.add_app": "Uygulama Ekle…",
            "awake.auto_section": "Otomatik uyanık tut",
            "awake.auto_footer": "Bunlardan biri gerçekleşince Mac kendiliğinden uyanık kalır; yukarıdaki anahtar ve süreler de çalışmaya devam eder. İndirmeler, İndirilenler klasöründeki yarım dosyalardan anlaşılır.",
            "awake.display_sleep": "Ekran uyuyabilsin",
            "awake.display_sleep_desc": "Mac çalışmaya devam etsin (indirme, render, müzik) ama ekran kapanabilsin.",
            "awake.lid": "Kapak kapalıyken de uyanık kal",
            "awake.lid_desc": "Mac şarja takılıyken çalışır — macOS pilde kapak kapanınca her zaman uyur.",
            "awake.options_section": "Seçenekler",
            "displays.keys_title": "Parlaklık ve ses tuşları monitörü kontrol etsin",
            "displays.keys_desc": "Klavyedeki parlaklık tuşları imlecin olduğu ekranı, ses tuşları monitörün hoparlörünü (DDC) ayarlar. Dahili ekran her zamanki gibi çalışır.",
            "displays.keys_section": "Klavye",
            "displays.schedule_title": "Gündüz ve gece parlaklığı",
            "displays.schedule_desc": "Seçtiğin saatlerde tüm ekranları gündüz ya da gece seviyesine geçirir. Aradaki değişikliklerin korunur.",
            "displays.schedule_section": "Zamanlama",
            "displays.schedule_day": "Gündüz başlangıcı",
            "displays.schedule_night": "Gece başlangıcı",
            "meetings.title": "Yaklaşan toplantılar",
            "meetings.desc": "Sıradaki etkinliği notch'ta ve hızlı panelde gösterir; başlamadan 5 dakika önce notch'u açar ve Zoom, Meet, Teams bağlantıları için Katıl düğmesi sunar.",
            "meetings.no_access": "Augment henüz takvimlerini okuyamıyor.",
            "meetings.join": "Katıl",
            "meetings.now": "Şimdi",
            "meetings.in_minutes": "%d dk sonra",
            "meetings.today": "Bugün",
            "perm.open_settings": "Ayarları Aç",
            "screenshots.title": "Ekran görüntüleri rafa",
            "screenshots.desc": "Yeni ekran görüntüleri notch rafına düşer; oradan doğrudan sohbete ya da e-postaya sürükleyebilirsin.",
            "notch.extras_section": "Notch'ta daha fazlası",
            "clip.panel_title": "Pano paneli (⇧⌘V)",
            "clip.panel_desc": "Pano geçmişinde ara, sık kullandıklarını sabitle, Return ya da ⌘1–⌘9 ile yapıştır.",
            "clip.section": "Pano",
            "clip.search": "Panoda ara",
            "clip.hint": "Return yapıştırır · ⌘1–9 hızlı yapıştır · ⌘P sabitler · Esc kapatır",
            "clip.pin": "Sabitle",
            "finder.extra_title": "Yolu Kopyala ve Terminal'de Aç",
            "finder.extra_desc": "İkisini de Finder'ın sağ tık menüsüne ekler.",
            "finder.extras_section": "Finder'da daha fazlası",
            "finderext.on": "Finder eklentisi açık",
            "finderext.off": "Finder eklentisi kapalı",
            "finderext.off_desc": "macOS bu eklentiyi kapalı kurar. Finder uzantıları arasından Augment'i aç — yoksa sağ tık öğeleri ve kesme rozeti görünmez.",
            "finderext.enable": "Aç…",
            "finderext.later": "Sonra",
            "finderext.alert_title": "Augment'in Finder eklentisini aç",
            "finderext.alert_body": "Finder'daki sağ tık öğeleri (Yeni Dosya, Yolu Kopyala, Terminal'de Aç) ve kesme rozeti Augment'in Finder eklentisine ihtiyaç duyar; macOS bu eklentiyi kapalı kurar. Aç'a tıkla ve açılan listede Augment'i etkinleştir.",
            "finder.copy_path": "Yolu Kopyala",
            "stats.title": "Sistem", "stats.cpu": "İşlemci", "stats.memory": "Bellek", "stats.network": "Ağ",
            "stats.temperature": "Sıcaklık",
            "stats.thermal_nominal": "Normal", "stats.thermal_fair": "Ilık", "stats.thermal_serious": "Sıcak", "stats.thermal_critical": "Çok sıcak",
            "finder.new_text_name": "adsız",
            "tour.welcome_title": "Augment'e hoş geldin",
            "tour.welcome_body": "macOS'ta eksik kalan küçük dokunuşlar — Dock, pencereler, Finder, notch, ses ve ekranlar için. Her şey kapalı başlar: istediğini aç; Augment bir izne yalnızca o özellik gerçekten ihtiyaç duyduğunda sorar.",
            "tour.panel_title": "Hızlı panel",
            "tour.panel_body": "Menü çubuğundaki Augment ikonuna tıkla: tüm ekranların parlaklığı, ses ve uygulama başına ses, mikrofon ve Uyanık Tut. Augment menüsü için ikona sağ tıkla.",
            "tour.notch_title": "Notch",
            "tour.notch_body": "İmleci çentiğe götür: müzik, dosya rafı, pano, not ve Pomodoro, ayrıca parlaklık ve ses. Dosyaları notch'a sürükleyip sakla, AirDrop ile gönder ya da zip yap.",
            "tour.windows_title": "Dock ve pencereler",
            "tour.windows_body": "Dock'taki bir ikonun üzerine gelip pencerelerini önizle, küçük resimli pencere seçici için ⌥Tab, yaslamak için ⌘← →, yerleşimler için ⌃⌥Space.",
            "tour.finder_title": "Finder",
            "tour.finder_body": "Sağ tık: Yeni Dosya ya da Klasör, Yolu Kopyala, Terminal'de Aç; ⌘X ile gerçek kesme. Bunlar için Augment'in Finder eklentisinin açık olması gerekir.",
            "tour.ready_title": "Hazırsın",
            "tour.ready_body": "Ayarlar'ı aç ve istediğin özellikleri etkinleştir. Bu turu Augment menüsünden tekrar açabilirsin.",
            "tour.next": "Devam",
            "tour.back": "Geri",
            "tour.skip": "Atla",
            "tour.open_settings": "Ayarları Aç",
            "menu.tour": "Hızlı Tur…",
            "finder.new_folder": "Klasör", "finder.new_folder_name": "adsız klasör",
            "finder.open_terminal": "Terminal'de Aç",
            "quick.all_displays": "Tüm ekranlar",
            "quick.mic_on": "Mikrofon açık",
            "quick.mic_off": "Mikrofon kapalı",
            "mixer.default_output": "Varsayılan çıkış",
            "mixer.pause_headphones": "Kulaklık çıkarılınca çalmayı duraklat",
            "mixer.pause_headphones_desc": "macOS'un kendi davranışı gibi: AirPods'u çıkarınca ya da kulaklığı sökünce müzik ve videolar hoparlörden devam etmek yerine durur.",
            "mixer.output_help": "Bu uygulamanın sesi nereden çalsın",
            "notch.awake_on": "Uyanık", "notch.awake_off": "Uyanık tut",
            "notch.awake_turn_off": "Kapat", "notch.awake_indefinite": "Ben kapatana kadar",
            "notch.awake_hours": "%d saat", "notch.awake_minutes": "%d dakika",
            "notch.awake_help": "Mac'i ve ekranı uyanık tutar. Süre seçmek için sağ tıkla.",
            "notch.hour_short": "sa", "notch.minute_short": "dk",
            "notch.tab_note": "Not", "notch.pomodoro_help": "Odak sayacı — süresini değiştirmek için sağ tıkla",
            "notch.pomodoro_length": "Pomodoro süresi", "notch.minutes_value": "%d dk",
            
            
            
            
            // Hover Pane
            
            "hover.delay": "Gecikme süresi",
            "hover.minimized": "Küçültüldü",
            "hover.timing": "Zamanlama",
            "hover.delay_desc": "Önizlemenin görünmesi için imlecin ne kadar süre Dock simgesi üzerinde kalması gerektiği.",
            "hover.appearance": "Görünüm",
            "hover.size": "Önizleme boyutu",
            "hover.suppress": "Boş önizlemeleri gizle",
            "hover.suppress_desc": "Çalışmayan veya penceresi olmayan uygulamalar için önizleme paneli gösterme.",
            "hover.header_actions": "Başlık eylemleri",
            "hover.header_actions_desc": "Başlığın üzerine gelindiğinde Tümünü Kapat / Tümünü Simge Durumuna Küçült kısayollarını göster.",
            "hover.magnify": "Boşluk tuşu ile büyüt",
            "hover.magnify_desc": "Önizleme açıkken büyütmek için Boşluk (Space) tuşuna basın. Önizleme açıkken diğer uygulamalar (örneğin Finder'ın Hızlı Bakış özelliği) bu tuş vuruşunu almaz.",
            "hover.interactions": "Etkileşimler",
            "hover.middle_click": "Orta tıklama pencereyi kapatır",
            "hover.middle_click_desc": "Tüm pencerelerini kapatmak için bir küçük resme (veya bir Dock simgesine) tekerlek tuşuyla tıklayın.",
            "hover.drag_out": "Sürükleyip odakla",
            "hover.drag_out_desc": "O pencereyi olduğu yerde odaklamak için küçük resmi panelin dışına sürükleyin.",
            "hover.instant": "Anında",
            "hover.minimize_all": "Tümünü Simge Durumuna Küçült",
            "hover.close_all": "Tümünü Kapat",
            "hover.no_open_windows": "Açık pencere yok",

            // Window Controls Pane
            
            "controls.show": "Pencere kontrollerini göster",
            "controls.show_desc": "Üzerine gelindiğinde macOS ile uyumlu kapatma, simge durumuna küçültme ve büyütme noktaları görünür.",
            "controls.side": "Kenar",
            "controls.force_quit": "Zorla kapat butonu",
            "controls.force_quit_desc": "Her önizlemenin karşı köşesinde yok edici bir şimşek simgesi gösterir.",
            "controls.legacy": "Klasik kapatma simgesi",
            "controls.legacy_desc": "Pencere kontrolleri kapalıyken, üzerine gelindiğinde küçük × simgesini göster.",
            "controls.layout": "Düzen",
            // Dock Click Pane
            
            "dock_click.behavior": "Tıklama Davranışı",
            "dock_click.toggle_minimize": "Dock tıklamasında küçültmeyi aç/kapat",
            "dock_click.toggle_minimize_desc": "Etkin uygulamanın Dock simgesine tıklayarak pencerelerini gizleyin; geri getirmek için tekrar tıklayın. Diğer uygulamalar standart macOS davranışını korur.",
            
            
            // Finder Pane
            
            "finder.menu": "\u{201C}Augment ile Yeni Dosya\u{201D} menüsü",
            "finder.menu_desc": "Finder'a kategorize edilmiş bağlamsal menüyü ekler.",
            "finder.folder_ql": "Klasör Hızlı Bakış hiyerarşisi",
            "finder.folder_ql_desc": "Klasör ağacını, boyutlarını ve özetlerini görmek için bir klasör üzerinde Boşluk tuşuna basın.",
            "finder.warning": "Devre dışıyken uyarı göster",
            "finder.warning_desc": "Kapalıysa, macOS Augment'in \u{201C}özellik kapalı\u{201D} mesajı yerine varsayılan klasör simgesini gösterir.",
            "finder.behavior": "Davranış",
            "finder.footer": "Finder/Hızlı Bakış uzantıları macOS tarafından yönetilir. Bunları açıp kapattıktan sonra, menünün yenilenmesi için Finder'da bir kez sağ tıklamanız gerekebilir.",
            "finder.menu_title": "Augment ile Yeni Dosya",
            "finder.category_coding": "Yazılım / Kodlama",
            "finder.category_office": "Microsoft Office",
            "finder.category_data": "Veri",
            "finder.category_project": "Proje Dosyaları",
            "finder.category_text": "Metin",
            "finder.template_word": "Word Belgesi (.docx)",
            "finder.template_excel": "Excel Çalışma Kitabı (.xlsx)",
            "finder.template_rtf": "Zengin Metin (.rtf)",
            "finder.template_env": "Ortam Değişkenleri (.env)",
            "finder.template_txt": "Düz Metin (.txt)",
            "finder.error_cannot_determine_title": "Dosya oluşturulamadı",
            "finder.error_cannot_determine_msg": "Augment hangi klasörün kullanılacağını belirleyemedi. Lütfen tekrar sağ tıklayıp deneyin.",
            "finder.error_generic_title": "Dosya oluşturulamadı",
            "finder.error_no_permission": "Augment'in bu konuma yazma izni yok. Başka bir klasör deneyin veya Gizlilik ayarlarından erişim izni verin.",
            "finder.error_read_only": "Bu disk salt okunur olduğundan burada yeni bir dosya oluşturulamaz.",
            // Displays Pane
            
            "displays.lock": "Dock'u seçilen ekranlara kilitle",
            "displays.lock_desc": "Augment diğer ekranlardaki Dock etkileşimlerini yoksayar ve imleci Dock çağırma bölgesinin dışına çıkarır, böylece macOS Dock'u seçilmemiş bir ekrana kaydırmaz.",
            "displays.dock_lock": "Dock Kilidi",
            "displays.connected": "Bağlı Ekranlar",
            "displays.refresh": "Ekran listesini yenile",
            "displays.fallback": "Herhangi bir ekran seçilmezse, Augment imlecin altındaki ekrana geri döner.",
            "displays.id": "Ekran ID",
            
            "displays.section": "Ekranlar", "displays.rescan": "Yeniden tara",
            "displays.none": "Ekran bulunamadı.",
            "displays.footer": "Dahili ve Apple ekranlarında macOS'un kendi parlaklığı kullanılır. Diğer monitörler DDC/CI ile kontrol edilir (MonitorControl gibi); desteklemeyen monitörlerde Augment görüntüyü karartır.",
            "displays.method_native": "Dahili kontrol", "displays.method_ddc": "DDC/CI", "displays.method_software": "Yazılımla karartma",
            "quick.displays": "Ekranlar", "quick.sound": "Ses",
            "quick.enable_mixer": "Uygulama bazında ses: Ses Mikseri'ni aç",
            "quick.awake_off_title": "Kapalı", "quick.awake_remaining": "%@ kaldı",
            "quick.off": "Kapalı", "quick.awake_duration": "Süre",
            
            
            
            
            // Snapping Pane
            
            "snapping.enable": "Pencere hizalamayı etkinleştir",
            "snapping.enable_desc": "Pencereleri yarım boyuta getirmek veya ekranı kaplamak için klavye kısayollarını kullanın.",
            "snapping.toggle": "Ana Açma/Kapama",
            "snapping.press": "Kısayola basın…",
            "snapping.change": "Değiştir",
            "snapping.reset_help": "Varsayılana sıfırla",
            "snapping.shortcuts": "Kısayollar",
            "snapping.shortcuts_desc": "Bir yönün yanındaki \"Değiştir\" seçeneğine tıklayın, ardından istediğiniz tuş kombinasyonuna basın. Varsayılanlar ⌘ + Yön Tuşlarıdır.",
            "snapping.preview": "Önizleme",
            "snapping.left": "Sol",
            "snapping.right": "Sağ",
            
            "snapping.left_half": "Sol Yarı",
            "snapping.right_half": "Sağ Yarı",
            "snapping.maximize": "Ekranı Kapla",
            "snapping.restore_center": "Geri Yükle / Ortala",

            // Cut & Paste
            "cutpaste.file_title": "Finder Dosya Kesme",
            "cutpaste.file_desc": "Finder'a gerçek bir Kes (⌘X) ekler: kesilen öğelerde makas rozeti görünür, başka klasörde ⌘V ile taşınır, ⌘Z ile geri gelir. Yapıştırmadan önce Esc veya ⌘Z kesmeyi iptal eder.",

            "snaplayouts.section": "Snap Layouts",
            "snaplayouts.title": "Yerleşim Seçici",
            "snaplayouts.desc": "Windows 11 tarzı bir açılır panel — yarım, çeyrek ve üçte bir bölgeler arasından seçip odaktaki pencereyi oraya yerleştirin.",
            "snaplayouts.trigger": "Seçiciyi göster",
            "snaplayouts.footer": "Kısayola pencerenin gitmesini istediğin yerin yakınında bas — seçici imlecin yanında açılır. Escape iptal eder.",

            "switcher.section": "Pencere Değiştirici",
            "switcher.title": "Küçük Resimli Pencere Değiştirici",
            "switcher.desc": "Option'a basılı tutup Tab'a dokunarak açık her pencerenin canlı küçük resmi arasında gezin, Option'ı bırakınca oraya geçin.",
            "switcher.trigger": "Değiştiriciyi göster",
            "switcher.footer": "⌘Tab yerine ⌥Tab'a bağlıdır, böylece sistemin kendi Uygulama Değiştirici'sine hiç dokunulmaz — bu, uygulama değil, tek tek pencereler arasında geçiş yapar.",

            
            "mixer.toggle": "Ses Mikseri",
            "mixer.enable": "Ses Mikserini Etkinleştir",
            "mixer.enable_desc": "Sistem sesinden bağımsız olarak her uygulama için ayrı bir ses seviyesi ayarlayın.",
            "mixer.footer": "macOS 14.2+'nin Core Audio process-tap API'sini kullanır (sanal ses sürücüsü yok, özel/gizli API yok) — açık kaynaklı Mac ses mikserlerinin kullandığı aynı teknik. macOS 14.2 veya üstü gerektirir.",
            "mixer.apps": "Çalışan Uygulamalar",
            "mixer.no_apps": "Şu anda ses çalan bir uygulama yok.",
            "mixer.unsupported": "Ses Mikseri için macOS 14.2 veya üstü gerekiyor.",

            // Notch Pane
            "notch.title": "Etkileşimli Çentik",
            "notch.subtitle": "MacBook kamera çentiğini müzik, pil ve dosyalar için dinamik bir merkeze dönüştürün.",
            "notch.enable": "Etkileşimli Çentiği Etkinleştir",
            "notch.enable_desc": "Fiziksel çentiğin arkasında duran genişletilebilir bir katman göster.",
            "notch.no_notch": "Çentikli ekran algılanmadı. Bu özellik, kamera çentiği olan bir MacBook (2021 veya sonrası) gerektirir.",
            "notch.toggle": "Ana Açma/Kapama",
            "notch.music": "Müzik ve Medya aracı",
            "notch.music_desc": "Sistem uygulamalarında çalan medyayı gösterir.",
            "notch.playback": "Oynatma kontrollerini göster",
            "notch.app_icon": "Kaynak uygulama simgesini göster",
            "notch.album_art": "Albüm görselini göster",
            "notch.hover": "Gecikme süresi",
            "notch.battery": "Pil göstergesi",
            "notch.battery_desc": "Apple tarzı pil seviyesi ve şarj durumu.",
            "notch.battery_style": "Pil stili",
            "notch.gauge": "Gösterge",
            "notch.symbol": "Sembol",
            "notch.percent": "Yüzde",
            "notch.calendar": "Takvim aracı",
            "notch.calendar_desc": "Mevcut günü ve tarihi gösterir.",
            "notch.calendar_style": "Takvim stili",
            "notch.compact": "Kompakt",
            "notch.badge": "Rozet",
            "notch.text": "Metin",
            "notch.shelf": "Dosya rafı",
            "notch.shelf_desc": "Hızlı erişim için dosyaları çentiğe sürükleyin; açmak için çift tıklayın.",
            "notch.widgets": "Araçlar",
            "notch.widgets_desc": "Çentiği genişletmek ve araçlarınızı görmek için çentik alanının üzerine gelin. Rafı kullanmak için dosyaları üzerine sürükleyin.",
            "notch.preview": "Önizleme",
            "notch.no_widgets": "Seçili araç yok",
            
            "notch.caffeinate": "Uykuda Kalma Düğmesi",
            "notch.caffeinate_desc": "Çentiğin üst çubuğunda Mac'i uyanık tutan bir düğme gösterir.",
            "notch.clipboard": "Pano Geçmişi",
            "notch.clipboard_desc": "Dosya rafının yanına, son kopyaladıklarınızı gösteren bir Pano sekmesi ekler.",
            "notch.shelf_tab_files": "Dosyalar",
            "notch.shelf_tab_clipboard": "Pano",
            "notch.clipboard_empty": "Henüz bir şey kopyalanmadı.",
            "notch.productivity": "Hızlı Not & Pomodoro",
            "notch.productivity_desc": "Çentiğin içinde bir not defteri ve odaklanma zamanlayıcısı.",
            "notch.quick_note_placeholder": "Hızlı not…",
            
            "notch.pomodoro_done": "Pomodoro tamamlandı 🍅",
            "notch.drop_files": "Dosyaları sabitlemek için bırakın",
            "notch.open": "Aç",
            "notch.reveal": "Finder'da Göster",
            "notch.copy": "Dosyayı Kopyala",
            "notch.remove": "Kaldır",
            // Permissions Pane
            "permissions.title": "İzinler",
            
            
            
            
            
            // Enums
            "size.small": "Küçük",
            "size.standard": "Standart",
            "size.large": "Büyük",
            "side.left": "Sol",
            "side.right": "Sağ",
            "click.toggle_minimize": "Küçültmeyi Aç/Kapat",
            "click.close_all_windows": "Tüm Pencereleri Kapat",
            "click.quit_app": "Uygulamadan Çık",
            "click.system_default": "Sistem Varsayılanı",
            "click.toggle_minimize_subtitle": "Gizlemek için tıklayın, pencereleri geri getirmek için tekrar tıklayın.",
            "click.close_all_windows_subtitle": "Etkin uygulamanın tüm standart pencerelerine kapatma eylemi gönderir.",
            "click.quit_app_subtitle": "Uygulamanın çıkmasını ister, ⌘Q gibi.",
            "click.system_default_subtitle": "Augment tıklamayı engellemez; macOS normal şekilde işler.",
            "effect.system": "Sistem",
            "effect.genie": "Genie (Sihirli Lamba)",
            "effect.scale": "Ölçekle",
            "effect.suck": "Yut",
            "effect.system_subtitle": "macOS genelindeki küçültme animasyonunu kullan.",
            "effect.genie_subtitle": "Klasik Dock'a kıvrılarak küçülme animasyonu.",
            "effect.scale_subtitle": "Genie'den daha hızlı, hızlı dikdörtgen şeklinde küçülme.",
            "effect.suck_subtitle": "Dock simgesine doğru kompakt girdap şeklinde küçülme."
        ]
    ]
}

