import Foundation

/// Single source of truth for App Group registration defaults.
///
/// Keep this list aligned with user-facing settings only; derived runtime
/// state should not be added here unless it is persisted across launches.
public enum PreferenceDefaults {
    public static let registrationValues: [String: Any] = [
        AppGroupKey.didCompleteOnboarding: false,
        AppGroupKey.hasRequestedAccessibilityPrompt: false,
        AppGroupKey.pendingFinderBridgeHostLaunch: false,
        AppGroupKey.appLanguage: "system",
        AppGroupKey.dockClickBehaviorEnabled: true,
        AppGroupKey.windowPreviewsEnabled: true,
        AppGroupKey.folderQuickLookEnabled: true,
        AppGroupKey.folderQuickLookShowWarning: true,
        AppGroupKey.finderNewFileMenuEnabled: true,
        AppGroupKey.dockLockEnabled: false,
        AppGroupKey.hoverOpenDelay: 0.4,
        AppGroupKey.previewSize: "standard",
        AppGroupKey.previewCloseButtonVisible: true,
        AppGroupKey.headerActionsEnabled: true,
        AppGroupKey.middleClickCloseEnabled: true,
        AppGroupKey.dragOutEnabled: true,
        AppGroupKey.spaceMagnifyEnabled: true,
        AppGroupKey.suppressEmptyPreviews: true,
        AppGroupKey.showHoverWhenMinimized: true,
        AppGroupKey.trafficLightEnabled: true,
        AppGroupKey.trafficLightSide: "trailing",
        AppGroupKey.killButtonVisible: false,
        AppGroupKey.minimizeEffect: "system",
        AppGroupKey.lockedScreenIDs: [String](),
        AppGroupKey.windowSnappingEnabled: false,
        AppGroupKey.windowSnappingShortcuts: "",
        AppGroupKey.notchEnabled: false,
        AppGroupKey.notchMusicWidget: true,
        AppGroupKey.notchBatteryWidget: true,
        AppGroupKey.notchShelfWidget: true,
        AppGroupKey.notchMediaControlsEnabled: true,
        AppGroupKey.notchShowAppIcon: true,
        AppGroupKey.notchShowAlbumArt: true,
        AppGroupKey.notchCalendarEnabled: true,
        AppGroupKey.notchCalendarStyle: "compact",
        AppGroupKey.notchBatteryStyle: "gauge",
        AppGroupKey.notchHoverDelay: 0.2,
        AppGroupKey.notchShelfURLs: [String]()
    ]
}

public enum Localizer {
    public static var currentLocale: Locale {
        let lang = (AppGroup.copySuiteValue(forKey: AppGroupKey.appLanguage) as? String) ?? "system"
        let localeLang: String
        if lang == "system" {
            let preferred = Locale.preferredLanguages.first ?? "en"
            let current: String
            if #available(macOS 13, iOS 16, tvOS 16, watchOS 9, *) {
                current = Locale.current.language.languageCode?.identifier ?? "en"
            } else {
                current = Locale.current.languageCode ?? "en"
            }
            let isTr = preferred.hasPrefix("tr") || current.hasPrefix("tr")
            localeLang = isTr ? "tr" : "en"
        } else {
            localeLang = lang
        }
        return Locale(identifier: localeLang)
    }

    public static func string(_ key: String) -> String {
        let localeLang = currentLocale.identifier
        return translations[localeLang]?[key] ?? translations["en"]?[key] ?? key
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "menu.about": "About Augment",
            "menu.settings": "Settings…",
            "menu.permissions": "Accessibility Permission…",
            "menu.quit": "Quit Augment",
            "settings.title": "Augment Settings",
            "about.description": "A focused utility for Dock, Finder and the notch.",
            "about.version": "Version",
            "about.dock_previews": "Dock previews",
            "about.finder_tools": "Finder tools",
            "about.interactive_notch": "Interactive notch",
            "about.close": "Close",
            "about.copyright": "Copyright",
            
            // General Pane
            "general.title": "Welcome to Augment",
            "general.subtitle": "Enhance your macOS workflow with live Dock hover previews, window snapping, Finder integrations, and a dynamic interactive Notch.",
            "general.features": "Features",
            "general.about": "About",
            "general.version": "Version",
            "general.build": "Build",
            "general.language": "Language",
            "general.lang_system": "System Language",
            "general.lang_en": "English",
            "general.lang_tr": "Türkçe",
            
            // Sidebar / tab titles
            "tab.general": "General",
            "tab.hover": "Hover",
            "tab.windowControls": "Window Controls",
            "tab.dockClick": "Dock Click",
            "tab.displays": "Displays",
            "tab.finder": "Finder",
            "tab.windowSnapping": "Snapping",
            "tab.notch": "Notch",
            "tab.permissions": "Permissions",

            // Feature titles & subtitles
            "feature.hover_title": "Window previews on Dock hover",
            "feature.hover_subtitle": "Live thumbnails appear when you linger on a Dock icon.",
            "feature.dockClick_title": "Toggle minimize on Dock click",
            "feature.dockClick_subtitle": "Click the active app's Dock icon to hide its windows; click again to bring them back. Other apps keep their macOS default behavior.",
            "feature.windowControls_title": "Window controls on previews",
            "feature.windowControls_subtitle": "Show macOS-style traffic lights on every hover thumbnail.",
            "feature.folderQL_title": "Folder Quick Look hierarchy",
            "feature.folderQL_subtitle": "Pressing Space on a folder shows its tree, sizes, and summaries.",
            "feature.finderMenu_title": "Finder \u{201C}New File with Augment\u{201D} menu",
            "feature.finderMenu_subtitle": "Adds a categorized contextual menu for creating files.",
            "feature.displays_title": "Pin Dock to selected displays",
            "feature.displays_subtitle": "Keep Augment's Dock interactions on one or more chosen monitors.",
            "feature.snapping_title": "Window snapping",
            "feature.snapping_subtitle": "Snap windows to screen halves with Cmd+Arrow keys (customizable).",
            "feature.notch_title": "Interactive Notch",
            "feature.notch_subtitle": "Transform the MacBook notch into a music, battery & file shelf hub.",
            
            // Hover Pane
            "hover.title": "Hover Previews",
            "hover.subtitle": "Tune how live window previews behave on Dock hover.",
            "hover.delay": "Hover delay",
            "hover.timing": "Timing",
            "hover.delay_desc": "How long the cursor needs to dwell on a Dock icon before the preview appears.",
            "hover.appearance": "Appearance",
            "hover.size": "Preview size",
            "hover.suppress": "Suppress empty previews",
            "hover.suppress_desc": "Never pop a panel for apps that aren't running or have no windows.",
            "hover.header_actions": "Header actions",
            "hover.header_actions_desc": "Hovering the title surfaces Close All / Minimize All shortcuts.",
            "hover.magnify": "Magnify on Space",
            "hover.magnify_desc": "Press Space while the hover preview is open to expand it. Other apps (for example Finder’s Quick Look) will not also receive that Space key while the preview is up.",
            "hover.interactions": "Interactions",
            "hover.middle_click": "Middle-click closes window",
            "hover.middle_click_desc": "Wheel-click a thumbnail (or a Dock icon) to close all of its windows.",
            "hover.drag_out": "Drag-out to focus",
            "hover.drag_out_desc": "Drag a thumbnail out of the panel to focus that window in place.",
            "hover.instant": "Instant",
            "hover.minimize_all": "Minimize All",
            "hover.close_all": "Close All",
            "hover.no_open_windows": "No open windows",

            // Window Controls Pane
            "controls.title": "Window Controls",
            "controls.subtitle": "macOS-style traffic lights live on every preview thumbnail.",
            "controls.show": "Show traffic-light controls",
            "controls.show_desc": "Close, minimize, and zoom dots appear on hover, matching macOS.",
            "controls.side": "Side",
            "controls.force_quit": "Force quit button",
            "controls.force_quit_desc": "Renders a destructive bolt icon on the opposite edge of every preview.",
            "controls.legacy": "Show legacy close glyph",
            "controls.legacy_desc": "When traffic lights are off, fall back to the small × button on hover.",
            "controls.layout": "Layout",
            
            // Dock Click Pane
            "dock_click.title": "Dock Click",
            "dock_click.subtitle": "Decide what happens when you click a Dock icon.",
            "dock_click.behavior": "Click Behaviour",
            "dock_click.toggle_minimize": "Toggle minimize on Dock click",
            "dock_click.toggle_minimize_desc": "Click the active app's Dock icon to hide its windows; click again to bring them back. Other apps keep their macOS default behavior.",
            "dock_click.effect_title": "Minimize Animation",
            "dock_click.effect_picker": "Minimize effect",
            "dock_click.effect_desc": "Choose “System” to leave macOS in charge of the animation; the other choices override the system preference and quickly restart the Dock.",
            
            // Finder Pane
            "finder.title": "Finder Integration",
            "finder.subtitle": "Right-click anywhere in Finder for a categorized \u{201C}New File with Augment\u{201D} menu.",
            "finder.menu": "\u{201C}New File with Augment\u{201D} menu",
            "finder.menu_desc": "Adds the categorized contextual menu in Finder.",
            "finder.folder_ql": "Folder Quick Look hierarchy",
            "finder.folder_ql_desc": "Press Space on a folder to see its tree, sizes, and summaries.",
            "finder.warning": "Show warning when disabled",
            "finder.warning_desc": "If off, macOS shows its default folder icon instead of Augment\u{2019}s \u{201C}feature off\u{201D} message.",
            "finder.behavior": "Behaviour",
            "finder.footer": "Finder/Quick Look extensions are managed by macOS. After toggling these, you may need to right-click in Finder once for the menu to refresh.",
            
            "finder.menu_title": "New File with Augment",
            "finder.category_coding": "Coding",
            "finder.category_office": "Microsoft Office",
            "finder.category_data": "Data",
            "finder.category_project": "Project Files",
            "finder.category_text": "Text",
            "finder.template_word": "Word Document (.docx)",
            "finder.template_excel": "Excel Workbook (.xlsx)",
            "finder.template_rtf": "Rich Text (.rtf)",
            "finder.template_env": "Environment (.env)",
            "finder.template_txt": "Plain Text (.txt)",
            "finder.error_cannot_determine_title": "Cannot create file",
            "finder.error_cannot_determine_msg": "Augment couldn't determine which folder to use. Right-click again and try once more.",
            "finder.error_generic_title": "Could not create file",
            "finder.error_no_permission": "Augment doesn’t have permission to write in this location. Try another folder or grant access in Privacy settings.",
            "finder.error_read_only": "This volume is read-only, so a new file can’t be created here.",
            
            // Displays Pane
            "displays.title": "Displays",
            "displays.subtitle": "Keep the Dock on the screens you actually use.",
            "displays.lock": "Lock Dock to chosen displays",
            "displays.lock_desc": "Augment ignores Dock interactions on other screens and lifts the cursor out of their Dock-summon zone, so macOS won't slide the Dock onto a non-selected display.",
            "displays.dock_lock": "Dock Lock",
            "displays.connected": "Connected Displays",
            "displays.refresh": "Refresh display list",
            "displays.fallback": "If no display is selected, Augment falls back to the screen under the cursor.",
            "displays.id": "Display ID",
            
            // Snapping Pane
            "snapping.title": "Window Snapping",
            "snapping.subtitle": "Snap windows to screen edges with keyboard shortcuts, just like Windows.",
            "snapping.enable": "Enable window snapping",
            "snapping.enable_desc": "Use keyboard shortcuts to tile windows to halves or maximize them.",
            "snapping.toggle": "Master Toggle",
            "snapping.press": "Press shortcut…",
            "snapping.change": "Change",
            "snapping.reset_help": "Reset to default",
            "snapping.shortcuts": "Shortcuts",
            "snapping.shortcuts_desc": "Click \"Change\" next to a direction, then press your desired key combination. Defaults are ⌘ + Arrow Keys.",
            "snapping.preview": "Preview",
            "snapping.left": "Left",
            "snapping.right": "Right",
            "snapping.up": "Up",
            "snapping.down": "Down",
            "snapping.left_half": "Left Half",
            "snapping.right_half": "Right Half",
            "snapping.maximize": "Maximize",
            "snapping.restore_center": "Restore / Center",
            
            // Notch Pane
            "notch.title": "Interactive Notch",
            "notch.subtitle": "Turn the MacBook camera notch into a dynamic hub for music, battery & files.",
            "notch.enable": "Enable Interactive Notch",
            "notch.enable_desc": "Show an expandable overlay that sits behind the physical notch.",
            "notch.no_notch": "No notched display detected. This feature requires a MacBook with a camera notch (2021 or later).",
            "notch.toggle": "Master Toggle",
            "notch.music": "Music & Media widget",
            "notch.music_desc": "Shows the currently playing media from system apps.",
            "notch.playback": "Show playback controls",
            "notch.app_icon": "Show source app icon",
            "notch.album_art": "Show album art",
            "notch.hover": "Hover delay",
            "notch.battery": "Battery indicator",
            "notch.battery_desc": "Apple-style battery level and charging status.",
            "notch.battery_style": "Battery style",
            "notch.gauge": "Gauge",
            "notch.symbol": "Symbol",
            "notch.percent": "Percent",
            "notch.calendar": "Calendar widget",
            "notch.calendar_desc": "Shows the current day and date.",
            "notch.calendar_style": "Calendar style",
            "notch.compact": "Compact",
            "notch.badge": "Badge",
            "notch.text": "Text",
            "notch.shelf": "File shelf",
            "notch.shelf_desc": "Drag files onto the notch for quick access; double-click to open.",
            "notch.widgets": "Widgets",
            "notch.widgets_desc": "Hover over the notch area to expand it and see your widgets. Drag files onto it to use the shelf.",
            "notch.preview": "Preview",
            "notch.no_widgets": "No widgets selected",
            "notch.drop_files": "Drop files to pin",
            "notch.drop_here": "Drop here to pin",
            "notch.open": "Open",
            "notch.reveal": "Reveal in Finder",
            "notch.copy": "Copy File",
            "notch.remove": "Remove",
            
            // Permissions Pane
            "permissions.title": "Accessibility Permission",
            "permissions.subtitle": "Augment uses Accessibility to read window state and intercept Dock interactions.",
            "permissions.recheck": "Re-check",
            "permissions.reprompt": "Re-prompt",
            "permissions.settings": "Open System Settings",
            "permissions.status": "Status",
            "permissions.footer": "Augment uses Accessibility to draw window previews and intercept Dock clicks. Nothing is collected or transmitted.",
            "permissions.enabled": "Accessibility access enabled",
            "permissions.required": "Accessibility access required",
            "permissions.desc_enabled": "Augment can read window positions and intercept Dock clicks.",
            "permissions.desc_required": "Without Accessibility, hover previews and click toggling can't run.",
            
            // Enums
            "size.small": "Small",
            "size.standard": "Standard",
            "size.large": "Large",
            "side.left": "Left",
            "side.right": "Right",
            "click.toggle_minimize": "Toggle Minimize",
            "click.close_all_windows": "Close All Windows",
            "click.quit_app": "Quit App",
            "click.system_default": "System Default",
            "click.toggle_minimize_subtitle": "Click to hide, click again to bring windows back.",
            "click.close_all_windows_subtitle": "Sends the close action to every standard window of the active app.",
            "click.quit_app_subtitle": "Asks the app to quit, like ⌘Q.",
            "click.system_default_subtitle": "Augment doesn't intercept the click; macOS handles it as usual.",
            "effect.system": "System",
            "effect.genie": "Genie",
            "effect.scale": "Scale",
            "effect.suck": "Suck",
            "effect.system_subtitle": "Use the macOS-wide minimize animation.",
            "effect.genie_subtitle": "Classic curl-into-the-Dock animation.",
            "effect.scale_subtitle": "Quick rectangular shrink, faster than Genie.",
            "effect.suck_subtitle": "Compact swirl into the Dock icon."
        ],
        "tr": [
            "menu.about": "Augment Hakkında",
            "menu.settings": "Ayarlar…",
            "menu.permissions": "Erişilebilirlik İzni…",
            "menu.quit": "Augment'ten Çık",
            "settings.title": "Augment Ayarları",
            "about.description": "Dock, Finder ve çentik (notch) için pratik araçlar.",
            "about.version": "Sürüm",
            "about.dock_previews": "Dock önizlemeleri",
            "about.finder_tools": "Finder araçları",
            "about.interactive_notch": "Etkileşimli çentik",
            "about.close": "Kapat",
            "about.copyright": "Telif Hakkı",
            
            // General Pane
            "general.title": "Augment'e Hoş Geldiniz",
            "general.subtitle": "Canlı Dock önizlemeleri, pencere hizalama (snapping), Finder entegrasyonları ve dinamik kamera çentiği (Notch) ile macOS iş akışınızı zenginleştirin.",
            "general.features": "Özellikler",
            "general.about": "Hakkında",
            "general.version": "Sürüm",
            "general.build": "Yapı",
            "general.language": "Dil",
            "general.lang_system": "Sistem Dili",
            "general.lang_en": "English",
            "general.lang_tr": "Türkçe",
            
            // Sidebar / tab titles
            "tab.general": "Genel",
            "tab.hover": "Üzerine Gelme",
            "tab.windowControls": "Pencere Kontrolleri",
            "tab.dockClick": "Dock Tıklaması",
            "tab.displays": "Ekranlar",
            "tab.finder": "Finder",
            "tab.windowSnapping": "Hizalama",
            "tab.notch": "Çentik",
            "tab.permissions": "İzinler",

            // Feature titles & subtitles
            "feature.hover_title": "Dock simgesi üzerinde pencere önizlemeleri",
            "feature.hover_subtitle": "Bir Dock simgesinin üzerinde beklediğinizde canlı küçük resimler görünür.",
            "feature.dockClick_title": "Dock tıklamasında küçültmeyi aç/kapat",
            "feature.dockClick_subtitle": "Etkin uygulamanın Dock simgesine tıklayarak pencerelerini gizleyin; geri getirmek için tekrar tıklayın. Diğer uygulamalar standart macOS davranışını korur.",
            "feature.windowControls_title": "Önizlemelerde pencere kontrolleri",
            "feature.windowControls_subtitle": "Her önizleme görselinde macOS tarzı pencere kontrollerini göster.",
            "feature.folderQL_title": "Klasör Hızlı Bakış hiyerarşisi",
            "feature.folderQL_subtitle": "Bir klasör üzerinde Boşluk tuşuna basıldığında klasör ağacını, boyutlarını ve özetlerini gösterir.",
            "feature.finderMenu_title": "Finder \u{201C}Augment ile Yeni Dosya\u{201D} menüsü",
            "feature.finderMenu_subtitle": "Dosya oluşturmak için kategorize edilmiş bağlamsal bir menü ekler.",
            "feature.displays_title": "Dock'u seçili ekranlara sabitle",
            "feature.displays_subtitle": "Augment'in Dock etkileşimlerini seçilen bir veya daha fazla monitörde tutun.",
            "feature.snapping_title": "Pencere hizalama (snapping)",
            "feature.snapping_subtitle": "Cmd+Yön tuşları ile pencereleri ekranın yarılarına hizalayın (özelleştirilebilir).",
            "feature.notch_title": "Etkileşimli Çentik",
            "feature.notch_subtitle": "MacBook çentiğini müzik, pil ve dosya rafı merkezine dönüştürün.",
            
            // Hover Pane
            "hover.title": "Üzerine Gelme Önizlemeleri",
            "hover.subtitle": "Dock üzerinde gezinirken canlı pencere önizlemelerinin nasıl davranacağını ayarlayın.",
            "hover.delay": "Gecikme süresi",
            "hover.timing": "Zamanlama",
            "hover.delay_desc": "Önizlemenin görünmesi için imlecin ne kadar süre Dock simgesi üzerinde kalması gerektiği.",
            "hover.appearance": "Görünüm",
            "hover.size": "Önizleme boyutu",
            "hover.suppress": "Boş önizlemeleri gizle",
            "hover.suppress_desc": "Çalışmayan veya penceresi olmayan uygulamalar için önizleme paneli gösterme.",
            "hover.header_actions": "Başlık eylemleri",
            "hover.header_actions_desc": "Başlığın üzerine gelindiğinde Tümünü Kapat / Tümünü Simge Durumuna Küçült kısayollarını göster.",
            "hover.magnify": "Boşluk tuşu ile büyüt",
            "hover.magnify_desc": "Önizleme açıkken büyütmek için Boşluk (Space) tuşuna basın. Önizleme açıkken diğer uygulamalar (örneğin Finder'ın Hızlı Bakış özelliği) bu tuş vuruşunu almaz.",
            "hover.interactions": "Etkileşimler",
            "hover.middle_click": "Orta tıklama pencereyi kapatır",
            "hover.middle_click_desc": "Tüm pencerelerini kapatmak için bir küçük resme (veya bir Dock simgesine) tekerlek tuşuyla tıklayın.",
            "hover.drag_out": "Sürükleyip odakla",
            "hover.drag_out_desc": "O pencereyi olduğu yerde odaklamak için küçük resmi panelin dışına sürükleyin.",
            "hover.instant": "Anında",
            "hover.minimize_all": "Tümünü Simge Durumuna Küçült",
            "hover.close_all": "Tümünü Kapat",
            "hover.no_open_windows": "Açık pencere yok",

            // Window Controls Pane
            "controls.title": "Pencere Kontrolleri",
            "controls.subtitle": "Her önizleme küçük resminde macOS tarzı pencere kontrol noktaları bulunur.",
            "controls.show": "Pencere kontrollerini göster",
            "controls.show_desc": "Üzerine gelindiğinde macOS ile uyumlu kapatma, simge durumuna küçültme ve büyütme noktaları görünür.",
            "controls.side": "Kenar",
            "controls.force_quit": "Zorla kapat butonu",
            "controls.force_quit_desc": "Her önizlemenin karşı köşesinde yok edici bir şimşek simgesi gösterir.",
            "controls.legacy": "Klasik kapatma simgesi",
            "controls.legacy_desc": "Pencere kontrolleri kapalıyken, üzerine gelindiğinde küçük × simgesini göster.",
            "controls.layout": "Düzen",
            
            // Dock Click Pane
            "dock_click.title": "Dock Tıklaması",
            "dock_click.subtitle": "Bir Dock simgesine tıkladığınızda ne olacağına karar verin.",
            "dock_click.behavior": "Tıklama Davranışı",
            "dock_click.toggle_minimize": "Dock tıklamasında küçültmeyi aç/kapat",
            "dock_click.toggle_minimize_desc": "Etkin uygulamanın Dock simgesine tıklayarak pencerelerini gizleyin; geri getirmek için tekrar tıklayın. Diğer uygulamalar standart macOS davranışını korur.",
            "dock_click.effect_title": "Simge Durumuna Küçültme Animasyonu",
            "dock_click.effect_picker": "Küçültme efekti",
            "dock_click.effect_desc": "Animasyonu macOS'in kontrolüne bırakmak için “Sistem” seçeneğini belirleyin; diğer seçenekler sistem tercihini geçersiz kılar ve Dock'u hızlıca yeniden başlatır.",
            
            // Finder Pane
            "finder.title": "Finder Entegrasyonu",
            "finder.subtitle": "Kategorize edilmiş bir \u{201C}Augment ile Yeni Dosya\u{201D} menüsü için Finder'da herhangi bir yere sağ tıklayın.",
            "finder.menu": "\u{201C}Augment ile Yeni Dosya\u{201D} menüsü",
            "finder.menu_desc": "Finder'a kategorize edilmiş bağlamsal menüyü ekler.",
            "finder.folder_ql": "Klasör Hızlı Bakış hiyerarşisi",
            "finder.folder_ql_desc": "Klasör ağacını, boyutlarını ve özetlerini görmek için bir klasör üzerinde Boşluk tuşuna basın.",
            "finder.warning": "Devre dışıyken uyarı göster",
            "finder.warning_desc": "Kapalıysa, macOS Augment'in \u{201C}özellik kapalı\u{201D} mesajı yerine varsayılan klasör simgesini gösterir.",
            "finder.behavior": "Davranış",
            "finder.footer": "Finder/Hızlı Bakış uzantıları macOS tarafından yönetilir. Bunları açıp kapattıktan sonra, menünün yenilenmesi için Finder'da bir kez sağ tıklamanız gerekebilir.",
            
            "finder.menu_title": "Augment ile Yeni Dosya",
            "finder.category_coding": "Yazılım / Kodlama",
            "finder.category_office": "Microsoft Office",
            "finder.category_data": "Veri",
            "finder.category_project": "Proje Dosyaları",
            "finder.category_text": "Metin",
            "finder.template_word": "Word Belgesi (.docx)",
            "finder.template_excel": "Excel Çalışma Kitabı (.xlsx)",
            "finder.template_rtf": "Zengin Metin (.rtf)",
            "finder.template_env": "Ortam Değişkenleri (.env)",
            "finder.template_txt": "Düz Metin (.txt)",
            "finder.error_cannot_determine_title": "Dosya oluşturulamadı",
            "finder.error_cannot_determine_msg": "Augment hangi klasörün kullanılacağını belirleyemedi. Lütfen tekrar sağ tıklayıp deneyin.",
            "finder.error_generic_title": "Dosya oluşturulamadı",
            "finder.error_no_permission": "Augment'in bu konuma yazma izni yok. Başka bir klasör deneyin veya Gizlilik ayarlarından erişim izni verin.",
            "finder.error_read_only": "Bu disk salt okunur olduğundan burada yeni bir dosya oluşturulamaz.",
            
            // Displays Pane
            "displays.title": "Ekranlar",
            "displays.subtitle": "Dock'u gerçekten kullandığınız ekranlarda tutun.",
            "displays.lock": "Dock'u seçilen ekranlara kilitle",
            "displays.lock_desc": "Augment diğer ekranlardaki Dock etkileşimlerini yoksayar ve imleci Dock çağırma bölgesinin dışına çıkarır, böylece macOS Dock'u seçilmemiş bir ekrana kaydırmaz.",
            "displays.dock_lock": "Dock Kilidi",
            "displays.connected": "Bağlı Ekranlar",
            "displays.refresh": "Ekran listesini yenile",
            "displays.fallback": "Herhangi bir ekran seçilmezse, Augment imlecin altındaki ekrana geri döner.",
            "displays.id": "Ekran ID",
            
            // Snapping Pane
            "snapping.title": "Pencere Hizalama",
            "snapping.subtitle": "Pencereleri klavye kısayollarıyla ekran kenarlarına hizalayın (tıpkı Windows'taki gibi).",
            "snapping.enable": "Pencere hizalamayı etkinleştir",
            "snapping.enable_desc": "Pencereleri yarım boyuta getirmek veya ekranı kaplamak için klavye kısayollarını kullanın.",
            "snapping.toggle": "Ana Açma/Kapama",
            "snapping.press": "Kısayola basın…",
            "snapping.change": "Değiştir",
            "snapping.reset_help": "Varsayılana sıfırla",
            "snapping.shortcuts": "Kısayollar",
            "snapping.shortcuts_desc": "Bir yönün yanındaki \"Değiştir\" seçeneğine tıklayın, ardından istediğiniz tuş kombinasyonuna basın. Varsayılanlar ⌘ + Yön Tuşlarıdır.",
            "snapping.preview": "Önizleme",
            "snapping.left": "Sol",
            "snapping.right": "Sağ",
            "snapping.up": "Yukarı",
            "snapping.down": "Aşağı",
            "snapping.left_half": "Sol Yarı",
            "snapping.right_half": "Sağ Yarı",
            "snapping.maximize": "Ekranı Kapla",
            "snapping.restore_center": "Geri Yükle / Ortala",
            
            // Notch Pane
            "notch.title": "Etkileşimli Çentik",
            "notch.subtitle": "MacBook kamera çentiğini müzik, pil ve dosyalar için dinamik bir merkeze dönüştürün.",
            "notch.enable": "Etkileşimli Çentiği Etkinleştir",
            "notch.enable_desc": "Fiziksel çentiğin arkasında duran genişletilebilir bir katman göster.",
            "notch.no_notch": "Çentikli ekran algılanmadı. Bu özellik, kamera çentiği olan bir MacBook (2021 veya sonrası) gerektirir.",
            "notch.toggle": "Ana Açma/Kapama",
            "notch.music": "Müzik ve Medya aracı",
            "notch.music_desc": "Sistem uygulamalarında çalan medyayı gösterir.",
            "notch.playback": "Oynatma kontrollerini göster",
            "notch.app_icon": "Kaynak uygulama simgesini göster",
            "notch.album_art": "Albüm görselini göster",
            "notch.hover": "Gecikme süresi",
            "notch.battery": "Pil göstergesi",
            "notch.battery_desc": "Apple tarzı pil seviyesi ve şarj durumu.",
            "notch.battery_style": "Pil stili",
            "notch.gauge": "Gösterge",
            "notch.symbol": "Sembol",
            "notch.percent": "Yüzde",
            "notch.calendar": "Takvim aracı",
            "notch.calendar_desc": "Mevcut günü ve tarihi gösterir.",
            "notch.calendar_style": "Takvim stili",
            "notch.compact": "Kompakt",
            "notch.badge": "Rozet",
            "notch.text": "Metin",
            "notch.shelf": "Dosya rafı",
            "notch.shelf_desc": "Hızlı erişim için dosyaları çentiğe sürükleyin; açmak için çift tıklayın.",
            "notch.widgets": "Araçlar",
            "notch.widgets_desc": "Çentiği genişletmek ve araçlarınızı görmek için çentik alanının üzerine gelin. Rafı kullanmak için dosyaları üzerine sürükleyin.",
            "notch.preview": "Önizleme",
            "notch.no_widgets": "Seçili araç yok",
            "notch.drop_files": "Dosyaları sabitlemek için bırakın",
            "notch.drop_here": "Sabitlemek için buraya bırakın",
            "notch.open": "Aç",
            "notch.reveal": "Finder'da Göster",
            "notch.copy": "Dosyayı Kopyala",
            "notch.remove": "Kaldır",
            
            // Permissions Pane
            "permissions.title": "Erişilebilirlik İzni",
            "permissions.subtitle": "Augment, pencere durumunu okumak ve Dock etkileşimlerini algılamak için Erişilebilirlik iznini kullanır.",
            "permissions.recheck": "Tekrar Kontrol Et",
            "permissions.reprompt": "Tekrar İste",
            "permissions.settings": "Sistem Ayarlarını Aç",
            "permissions.status": "Durum",
            "permissions.footer": "Augment, pencere önizlemelerini çizmek ve Dock tıklamalarını algılamak için Erişilebilirlik iznini kullanır. Hiçbir veri toplanmaz veya iletilmez.",
            "permissions.enabled": "Erişilebilirlik erişimi etkin",
            "permissions.required": "Erişilebilirlik erişimi gerekli",
            "permissions.desc_enabled": "Augment, pencere konumlarını okuyabilir ve Dock tıklamalarını algılayabilir.",
            "permissions.desc_required": "Erişilebilirlik olmadan, üzerine gelme önizlemeleri ve tıklama eylemleri çalışamaz.",
            
            // Enums
            "size.small": "Küçük",
            "size.standard": "Standart",
            "size.large": "Büyük",
            "side.left": "Sol",
            "side.right": "Sağ",
            "click.toggle_minimize": "Küçültmeyi Aç/Kapat",
            "click.close_all_windows": "Tüm Pencereleri Kapat",
            "click.quit_app": "Uygulamadan Çık",
            "click.system_default": "Sistem Varsayılanı",
            "click.toggle_minimize_subtitle": "Gizlemek için tıklayın, pencereleri geri getirmek için tekrar tıklayın.",
            "click.close_all_windows_subtitle": "Etkin uygulamanın tüm standart pencerelerine kapatma eylemi gönderir.",
            "click.quit_app_subtitle": "Uygulamanın çıkmasını ister, ⌘Q gibi.",
            "click.system_default_subtitle": "Augment tıklamayı engellemez; macOS normal şekilde işler.",
            "effect.system": "Sistem",
            "effect.genie": "Genie (Sihirli Lamba)",
            "effect.scale": "Ölçekle",
            "effect.suck": "Yut",
            "effect.system_subtitle": "macOS genelindeki küçültme animasyonunu kullan.",
            "effect.genie_subtitle": "Klasik Dock'a kıvrılarak küçülme animasyonu.",
            "effect.scale_subtitle": "Genie'den daha hızlı, hızlı dikdörtgen şeklinde küçülme.",
            "effect.suck_subtitle": "Dock simgesine doğru kompakt girdap şeklinde küçülme."
        ]
    ]
}

